# -*- coding: utf-8 -*-
from . import showroom_car_vehicle
from . import showroom_crm_lead
from . import showroom_res_config_settings
from . import service_customer_vehicle
from . import service_inspection_checklist_lines
from . import service_inspection_image_lines
from . import service_inspection_type
from . import service_parts_used_lines
from . import service_product_template
from . import service_booking
from . import service_type
from . import service_used_lines
from . import service_supervisor_user
from . import service_vehicle_brand
from . import service_vehicle_fuel_type
from . import service_vehicle_model
from . import service_vehicle_type
from . import res_partner
from . import service_booking_wizards
from . import service_showroom_dashboard
