from . import vehicle_brand
from . import service_booking
from . import vehicle_model
from . import vehicle_type
from . import customer_vehicle
from . import vehicle_fuel_type
from . import producttemplate
from . import car_vehicle
from . import crm_lead
from . import res_config_settings
